spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 10

  jpa:
    properties:
      javax.persistence.validation.mode: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.show_sql: true
      hibernate.connection.characterEncoding: utf8mb4
      hibernate.connection.CharSet: utf8mb4
      hibernate.connection.useUnicode: true
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
---
jwttoken:
  secret: secret
  expire: 1000000
