spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 10
---
jwttoken:
  secret: secret
  expire: 1000000